name: Gatsby Deploy

on:
  push:
    branches: main

env:
  GH_TOKEN: ${{ secrets.GH_PAGES }}
  OTHER_VAR: ${{ vars.GH_VAR }} 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Config
        run: |
          git config --global user.email "decheine@wisc.edu"
          git config --global user.name "decheine"
        shell: pwsh
        env:
          GIT_USER: ${{ vars.GITHUB_USER }}
          GIT_EMAIL: "decheine@wisc.edu"
          GIT_PASS: ${{ secrets.GH_PAGES_PASS }}
          OTHER_VAR: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm install
      - name: Deploy
        run: npm run deploy:ci
