name: Gatsby Deploy

on:
  push:
    branches: main

env:
  GH_TOKEN: ${{ secrets.GH_PAGES }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Config
        run: |
          git config --global user.email  ${{ secrets.GIT_EMAIL }}
          git config --global user.name  ${{ secrets.GIT_USER }}
          git config --global credential.helper "!f() { echo \`"username=`${{ secrets.GIT_USER }}`npassword=`${{ secrets.GIT_PASS }}\`"; }; f"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm install
      - name: Deploy
        run: npm run deploy:ci
